services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    restart: on-failure
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    restart: on-failure
    volumes:
      - wp_data:/var/www/html

  nginx:
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: on-failure

  adminer:
    container_name: adminer
    env_file: .env
    build: ./requirements/bonus/adminer
    networks:
      - inception
    restart: on-failure

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mysql

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
