services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    restart: on-failure
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    restart: on-failure
    volumes:
      - wp_data:/var/www/html

  nginx:
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: on-failure

  redis:
    container_name: redis
    env_file: .env
    build: ./requirements/bonus/redis
    networks:
      - inception
    restart: on-failure

  adminer:
    container_name: adminer
    env_file: .env
    build: ./requirements/bonus/adminer
    networks:
      - inception
    restart: on-failure

  static-site:
    container_name: static-site
    build: ./requirements/bonus/static-site
    networks:
      - inception
    restart: on-failure

  ftpserver:
    container_name: ftpserver
    env_file: .env
    build: ./requirements/bonus/ftpserver
    ports:
      - "21:21"
      - "50000-50099:50000-50099"
    networks:
      - inception
    restart: on-failure
    volumes:
      - wp_data:/var/www/html
    secrets:
      - ftp_user_password

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer
    restart: on-failure
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt

networks:
  inception:

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/portainer

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mysql

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
