FROM debian:bookworm

RUN apt-get update && apt-get install -y curl ca-certificates

RUN curl -L https://github.com/portainer/portainer/releases/download/2.21.4/portainer-2.21.4-linux-amd64.tar.gz \
    -o /tmp/portainer.tar.gz && \
    tar -xzf /tmp/portainer.tar.gz -C /opt && \
    rm /tmp/portainer.tar.gz

WORKDIR /opt/portainer

EXPOSE 9000

CMD ["./portainer"]
