FROM debian:bookworm

RUN apt-get update && apt-get install -y curl ca-certificates apache2-utils

RUN curl -L https://github.com/portainer/portainer/releases/download/2.21.4/portainer-2.21.4-linux-amd64.tar.gz \
    -o /tmp/portainer.tar.gz && \
    tar -xzf /tmp/portainer.tar.gz -C /opt && \
    rm /tmp/portainer.tar.gz

WORKDIR /opt/portainer

EXPOSE 9000
# CMD htpasswd -nbB admin "$(cat /run/secrets/portainer_admin_password)" | cut -d: -f2 > /tmp/hashed_password && exec ./portainer --admin-password-file /tmp/hashed_password
CMD ["./portainer", "--admin-password-file", "/run/secrets/portainer_admin_password"]
# CMD ["./portainer"]
