FROM debian:bookworm

RUN apt update -y && \
    apt install -y openssl \
    nginx

RUN mkdir -p /etc/nginx/ssl

ARG DOMAIN_NAME

RUN openssl req -x509 \
    -nodes -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out  /etc/nginx/ssl/nginx.crt \
    -days 365 \
    -subj "/CN=${DOMAIN_NAME}"

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]
